const dataImages = {
  actress: [
    { name: "agnez mo", imageUrl: "/guessmaster/images/aktris/aktris_agnez-mo.jpg" },
    { name: "amanda manopo", imageUrl: "/guessmaster/images/aktris/aktris_amanda-manopo.jpg" },
    { name: "aurelie moeremans", imageUrl: "/guessmaster/images/aktris/aktris_aurelie-moeremans.jpg" },
    { name: "chelsea islan", imageUrl: "/guessmaster/images/aktris/aktris_chelsea-islan.jpg" },
    { name: "cinta laura", imageUrl: "/guessmaster/images/aktris/aktris_cinta-laura.jpg" },
    { name: "citra kirana", imageUrl: "/guessmaster/images/aktris/aktris_citra-kirana.jpg" },
    { name: "maudy ayunda", imageUrl: "/guessmaster/images/aktris/aktris_maudy-ayunda.jpg" },
    { name: "natasha wilona", imageUrl: "/guessmaster/images/aktris/aktris_natasha-wilona.jpg" },
    { name: "niki zefanya", imageUrl: "/guessmaster/images/aktris/aktris_niki-zefanya.jpg" },
    { name: "syifa hadju", imageUrl: "/guessmaster/images/aktris/aktris_syifa-hadju.jpg" },
    { name: "velove vexia", imageUrl: "/guessmaster/images/aktris/aktris_velove-vexia.jpg" },
    { name: "adinda thomas", imageUrl: "/guessmaster/images/aktris/aktris_adinda-thomas.jpg" },
    { name: "agatha pricilla", imageUrl: "/guessmaster/images/aktris/aktris_agatha-pricilla.jpg" },
    { name: "alexa key", imageUrl: "/guessmaster/images/aktris/aktris_alexa-key.jpg" },
    { name: "amanda rawles", imageUrl: "/guessmaster/images/aktris/aktris_amanda-rawles.jpg" },
    { name: "amara lingua", imageUrl: "/guessmaster/images/aktris/aktris_Amara-Lingua.jpg" },
    { name: "angelica pieters", imageUrl: "/guessmaster/images/aktris/aktris_angelica-martha-pieters.jpg" },
    { name: "angel karamoy", imageUrl: "/guessmaster/images/aktris/aktris_angel-karamoy.jpg" },
    { name: "anisa rahma", imageUrl: "/guessmaster/images/aktris/aktris_anisa-rahma.jpg" },
    { name: "anya geraldine", imageUrl: "/guessmaster/images/aktris/aktris_anya-geraldine.jpg" },
    { name: "arafah rianti", imageUrl: "/guessmaster/images/aktris/aktris_arafah-rianti.jpg" },
    { name: "ariel tatum", imageUrl: "/guessmaster/images/aktris/aktris_ariel-tatum.jpg" },
    { name: "audi marissa", imageUrl: "/guessmaster/images/aktris/aktris_Audi-Marissa.jpg" },
    { name: "aulia sarah", imageUrl: "/guessmaster/images/aktris/aktris_aulia-sarah.jpg" },
    { name: "aura kasih", imageUrl: "/guessmaster/images/aktris/aktris_aura-kasih.jpg" },
    { name: "aura nabila", imageUrl: "/guessmaster/images/aktris/aktris_aura-nabila-izzathi.jpg" },
    { name: "ayu tingting", imageUrl: "/guessmaster/images/aktris/aktris_ayu-tinting.jpg" },
    { name: "ayya renita", imageUrl: "/guessmaster/images/aktris/aktris_ayya-renita.jpg" },
    { name: "bunga citra lestari", imageUrl: "/guessmaster/images/aktris/aktris_bunga-citra-lestari.jpg" },
    { name: "cindy yuvia", imageUrl: "/guessmaster/images/aktris/aktris_cindy-yuvia.jpg" },
    { name: "cupi cupita", imageUrl: "/guessmaster/images/aktris/aktris_cupi-cupita.jpg" },
    { name: "cut syifa", imageUrl: "/guessmaster/images/aktris/aktris_cut-syifa.jpg" },
    { name: "cut tari", imageUrl: "/guessmaster/images/aktris/aktris_cut-tari.jpg" },
    { name: "cyntiara alona", imageUrl: "/guessmaster/images/aktris/aktris_cyntiara-alona.jpg" },
    { name: "dewi gita", imageUrl: "/guessmaster/images/aktris/aktris_dewi-gita.jpg" },
    { name: "dewi persik", imageUrl: "/guessmaster/images/aktris/aktris_dewi-perssik.jpg" },
    { name: "dian sastro", imageUrl: "/guessmaster/images/aktris/aktris_dian-sastrowardoyo.jpg" },
    { name: "dinar candy", imageUrl: "/guessmaster/images/aktris/aktris_dinar-candy.jpg" },
    { name: "dinda kirana", imageUrl: "/guessmaster/images/aktris/aktris_dinda-kirana.jpg" },
    { name: "eriska rein", imageUrl: "/guessmaster/images/aktris/aktris_Eriska-Rein.jpg" },
    { name: "farah quinn", imageUrl: "/guessmaster/images/aktris/aktris_farah-quinn.jpg" },
    { name: "febby", imageUrl: "/guessmaster/images/aktris/aktris_febby-rastanty.jpg" },
    { name: "felicya angelista", imageUrl: "/guessmaster/images/aktris/aktris_felicya-angelista.jpg" },
    { name: "gisella anastasa", imageUrl: "/guessmaster/images/aktris/aktris_gisella-anastasa.jpg" },
    { name: "happy salma", imageUrl: "/guessmaster/images/aktris/aktris_happy-salma.jpg" },
    { name: "haruka", imageUrl: "/guessmaster/images/aktris/aktris_haruka-nakagawa.jpg" },
    { name: "ira wibowo", imageUrl: "/guessmaster/images/aktris/aktris_Ira-Wibowo.jpg" },
    { name: "irish bella", imageUrl: "/guessmaster/images/aktris/aktris_irish-bella.jpg" },
    { name: "isyana sarasvati", imageUrl: "/guessmaster/images/aktris/aktris_isyana-sarasvati.jpg" },
    { name: "jenita janet", imageUrl: "/guessmaster/images/aktris/aktris_isyana-sarasvati.jpg" },
    { name: "jessica iskandar", imageUrl: "/guessmaster/images/aktris/aktris_jessica-iscandar.jpg" },
    { name: "jessica mila", imageUrl: "/guessmaster/images/aktris/aktris_jessica-mila.jpg" },
    { name: "kimberly ryder", imageUrl: "/guessmaster/images/aktris/aktris_kimberly-ryder.jpg" },
    { name: "luna maya", imageUrl: "/guessmaster/images/aktris/aktris_luna-maya.jpg" },
    { name: "lyodra ginting", imageUrl: "/guessmaster/images/aktris/aktris_lyodora-ginting.jpg" },
    { name: "mala barbie", imageUrl: "/guessmaster/images/aktris/aktris_mala-barbie.jpg" },
    { name: "margin wieheerm", imageUrl: "/guessmaster/images/aktris/aktris_margin-wieheerm.jpg" },
    { name: "marion jola", imageUrl: "/guessmaster/images/aktris/aktris_marion-jola.jpg" },
    { name: "marsha timothy", imageUrl: "/guessmaster/images/aktris/aktris_marsha-timothy.jpg" },
    { name: "michelle ziudith", imageUrl: "/guessmaster/images/aktris/aktris_michelle-ziudith.jpg" },
    { name: "mikha tambayong", imageUrl: "/guessmaster/images/aktris/aktris_mikha-tambayong.jpg" },
    { name: "mpok alpa", imageUrl: "/guessmaster/images/aktris/aktris_mpok-alpa.jpg" },
    { name: "mpok atiek", imageUrl: "/guessmaster/images/aktris/aktris_mpok-atiek.jpg" },
    { name: "nabilah", imageUrl: "/guessmaster/images/aktris/aktris_nabilah-ayu-ratna.jpg" },
    { name: "nafa urbach", imageUrl: "/guessmaster/images/aktris/aktris_nafa-urbach.jpg" },
    { name: "nikita mirzani", imageUrl: "/guessmaster/images/aktris/aktris_nikita-mirzani.jpg" },
    { name: "nikita willy", imageUrl: "/guessmaster/images/aktris/aktris_nikita-willy.jpg" },
    { name: "nina zatulini", imageUrl: "/guessmaster/images/aktris/aktris_nina-zatulini.jpg" },
    { name: "nunung", imageUrl: "/guessmaster/images/aktris/aktris_nunung.jpg" },
    { name: "ochi rosdiana", imageUrl: "/guessmaster/images/aktris/aktris_ochi-rosdiana.jpg" },
    { name: "olivia jensen", imageUrl: "/guessmaster/images/aktris/aktris_olivia-jensen.jpg" },
    { name: "pamela bowie", imageUrl: "/guessmaster/images/aktris/aktris_pamela-bowie.jpg" },
    { name: "pamela safitri", imageUrl: "/guessmaster/images/aktris/aktris_pamela-safitri.jpg" },
    { name: "pevita pearce", imageUrl: "/guessmaster/images/aktris/aktris_pevita-pearce.jpg" },
    { name: "prilly latuconsina", imageUrl: "/guessmaster/images/aktris/aktris_prilly-latuconsina.jpg" },
    { name: "raisa", imageUrl: "/guessmaster/images/aktris/aktris_raisa.jpg" },
    { name: "raline shah", imageUrl: "/guessmaster/images/aktris/aktris_raline-shah.jpg" },
    { name: "ranty maria", imageUrl: "/guessmaster/images/aktris/aktris_ranty-maria.jpg" },
    { name: "rina nose", imageUrl: "/guessmaster/images/aktris/aktris_rina-nose.jpg" },
    { name: "sahila hisyam", imageUrl: "/guessmaster/images/aktris/aktris_sahila-hisyam.jpg" },
    { name: "sandrinna michelle", imageUrl: "/guessmaster/images/aktris/aktris_sandrinna-michelle.jpg" },
    { name: "shaarefa daaanish", imageUrl: "/guessmaster/images/aktris/aktris_shaarefa-daanish.jpg" },
    { name: "shita naomi", imageUrl: "/guessmaster/images/aktris/aktris_shinta-naomi.jpg" },
    { name: "sofia latjuba", imageUrl: "/guessmaster/images/aktris/aktris_sofia-latjuba.jpg" },
    { name: "soimah", imageUrl: "/guessmaster/images/aktris/aktris_soimah.jpg" },
    { name: "suzzana", imageUrl: "/guessmaster/images/aktris/aktris_suzzana.jpg" },
    { name: "sylvia fully", imageUrl: "/guessmaster/images/aktris/aktris_sylvia-fully.jpg" },
    { name: "tamara bleszynski", imageUrl: "/guessmaster/images/aktris/aktris_tamara-bleszynski.jpg" },
    { name: "tatjana saphira", imageUrl: "/guessmaster/images/aktris/aktris_tatjana-saphira.jpg" },
    { name: "tissa biani", imageUrl: "/guessmaster/images/aktris/aktris_tissa-biani.jpg" },
    { name: "titi kamal", imageUrl: "/guessmaster/images/aktris/aktris_tissa-biani.jpg" },
    { name: "valerie teresa", imageUrl: "/guessmaster/images/aktris/aktris_valerie-teresa.jpg" },
    { name: "vanesha prschilla", imageUrl: "/guessmaster/images/aktris/aktris_vanesha-preschilla.jpg" },
    { name: "vega darwanti", imageUrl: "/guessmaster/images/aktris/aktris_vega-darwanti.jpg" },
    { name: "wika salim", imageUrl: "/guessmaster/images/aktris/aktris_wika-salim.jpg" },
    { name: "wulan guritno", imageUrl: "/guessmaster/images/aktris/aktris_wulan-guritno.jpg" },
    { name: "yuki kato", imageUrl: "/guessmaster/images/aktris/aktris_yuki-kato.jpg" },
    { name: "yunita siregar", imageUrl: "/guessmaster/images/aktris/aktris_yunita-siregar.jpg" },
    { name: "zaskia gotik", imageUrl: "/guessmaster/images/aktris/aktris_zaskia-gotik.jpg" },
  ],
  actor: [
    { name: "andre taulany", imageUrl: "/guessmaster/images/aktor/aktor_andre-taulany.jpg" },
    { name: "deddy corbuzier", imageUrl: "/guessmaster/images/aktor/aktor_deddy-corbuzier.jpg" },
    { name: "iko uwais", imageUrl: "/guessmaster/images/aktor/aktor_iko-uwais.jpg" },
    { name: "joe taslim", imageUrl: "/guessmaster/images/aktor/aktor_joe-taslim.jpg" },
    { name: "raffi ahmad", imageUrl: "/guessmaster/images/aktor/aktor_raffi-ahmad.jpg" },
    { name: "reza rahardian", imageUrl: "/guessmaster/images/aktor/aktor_reza-rahardian.jpg" },
    { name: "rich brian", imageUrl: "/guessmaster/images/aktor/aktor_rich-brian.jpg" },
    { name: "sule", imageUrl: "/guessmaster/images/aktor/aktor_sule.jpg" },
    { name: "vino g bastian", imageUrl: "/guessmaster/images/aktor/aktor_vino-g-bastian.jpg" },
    { name: "yayan ruhian", imageUrl: "/guessmaster/images/aktor/aktor_yayan-ruhian.jpg" },
    { name: "abdel", imageUrl: "/guessmaster/images/aktor/aktor_abdel.jpg" },
    { name: "abimana aryasatya", imageUrl: "/guessmaster/images/aktor/aktor_abimana-aryasatya.jpg" },
    { name: "adipati dolken", imageUrl: "/guessmaster/images/aktor/aktor_adipati-dolken.jpg" },
    { name: "adul", imageUrl: "/guessmaster/images/aktor/aktor_adul.jpg" },
    { name: "aliando", imageUrl: "/guessmaster/images/aktor/aktor_aliando-syarief.jpg" },
    { name: "aming", imageUrl: "/guessmaster/images/aktor/aktor_aming.jpg" },
    { name: "andhika pratama", imageUrl: "/guessmaster/images/aktor/aktor_andhika-pratama.jpg" },
    { name: "arie kriting", imageUrl: "/guessmaster/images/aktor/aktor_arie-kriting.jpg" },
    { name: "arie untung", imageUrl: "/guessmaster/images/aktor/aktor_arie-untung.jpg" },
    { name: "aziz gagap", imageUrl: "/guessmaster/images/aktor/aktor_aziz-gagap.jpg" },
    { name: "babe cabita", imageUrl: "/guessmaster/images/aktor/aktor_babe-cabita.jpg" },
    { name: "baim wong", imageUrl: "/guessmaster/images/aktor/aktor_baim-wong.jpg" },
    { name: "bedu", imageUrl: "/guessmaster/images/aktor/aktor_bedu.jpg" },
    { name: "billy", imageUrl: "/guessmaster/images/aktor/aktor_Billy-syahputra.jpg" },
    { name: "bopak", imageUrl: "/guessmaster/images/aktor/aktor_bopak-castello.jpg" },
    { name: "caesar", imageUrl: "/guessmaster/images/aktor/aktor_caesar.jpg" },
    { name: "cak lontong", imageUrl: "/guessmaster/images/aktor/aktor_Cak-lontong.jpg" },
    { name: "chicco jerikho", imageUrl: "/guessmaster/images/aktor/aktor_chicco-jericco.jpg" },
    { name: "darto", imageUrl: "/guessmaster/images/aktor/aktor_darto.jpg" },
    { name: "daus mini", imageUrl: "/guessmaster/images/aktor/aktor_daus-mini.jpg" },
    { name: "daus separo", imageUrl: "/guessmaster/images/aktor/aktor_daus-separo.jpg" },
    { name: "denny cagur", imageUrl: "/guessmaster/images/aktor/aktor_denny-cagur.jpg" },
    { name: "denny sumargo", imageUrl: "/guessmaster/images/aktor/aktor_denny-sumargo.jpg" },
    { name: "desta", imageUrl: "/guessmaster/images/aktor/aktor_desta.jpg" },
    { name: "dicky chandra", imageUrl: "/guessmaster/images/aktor/aktor_dicky-chandra.jpg" },
    { name: "dimas aditya", imageUrl: "/guessmaster/images/aktor/aktor_dimas-aditya.jpg" },
    { name: "dimas anggara", imageUrl: "/guessmaster/images/aktor/aktor_dimas-anggara.jpg" },
    { name: "dion wiyoko", imageUrl: "/guessmaster/images/aktor/aktor_dion-wiyoko.jpg" },
    { name: "dono", imageUrl: "/guessmaster/images/aktor/aktor_dono.jpg" },
    { name: "gading marten", imageUrl: "/guessmaster/images/aktor/aktor_gading-marten.jpg" },
    { name: "gilang dirga", imageUrl: "/guessmaster/images/aktor/aktor_gilang-dirga.jpg" },
    { name: "indra bekti", imageUrl: "/guessmaster/images/aktor/aktor_indra-bekti.jpg" },
    { name: "indro", imageUrl: "/guessmaster/images/aktor/aktor_indro.jpg" },
    { name: "ivan gunawan", imageUrl: "/guessmaster/images/aktor/aktor_ivan-gunawan.jpg" },
    { name: "jefri nichol", imageUrl: "/guessmaster/images/aktor/aktor_jefri-nichol.jpg" },
    { name: "jeremy teti", imageUrl: "/guessmaster/images/aktor/aktor_jeremy-teti.jpg" },
    { name: "kasino", imageUrl: "/guessmaster/images/aktor/aktor_kasino.jpg" },
    { name: "kenta", imageUrl: "/guessmaster/images/aktor/aktor_kenta-yamaguchi.jpg" },
    { name: "komeng", imageUrl: "/guessmaster/images/aktor/aktor_komeng.jpg" },
    { name: "lee", imageUrl: "/guessmaster/images/aktor/aktor_lee.jpg" },
    { name: "marshall", imageUrl: "/guessmaster/images/aktor/aktor_marshall-sastra.jpg" },
    { name: "melki", imageUrl: "/guessmaster/images/aktor/aktor_melki-bajaj.jpg" },
    { name: "mongol", imageUrl: "/guessmaster/images/aktor/aktor_mongol.jpg" },
    { name: "olga", imageUrl: "/guessmaster/images/aktor/aktor_Olga-syahputra.jpg" },
    { name: "omesh", imageUrl: "/guessmaster/images/aktor/aktor_omesh.jpg" },
    { name: "opie kumis", imageUrl: "/guessmaster/images/aktor/aktor_opie-kumis.jpg" },
    { name: "parto", imageUrl: "/guessmaster/images/aktor/aktor_parto.jpg" },
    { name: "raditya dika", imageUrl: "/guessmaster/images/aktor/aktor_raditya-dika.jpg" },
    { name: "richard kyle", imageUrl: "/guessmaster/images/aktor/aktor_richard-kyle.jpg" },
    { name: "ricky harun", imageUrl: "/guessmaster/images/aktor/aktor_ricky-harun.jpg" },
    { name: "rikas harsa", imageUrl: "/guessmaster/images/aktor/aktor_rikas-harsa.jpg" },
    { name: "rio dewanto", imageUrl: "/guessmaster/images/aktor/aktor_rio-dewanto.jpg" },
    { name: "rizky febian", imageUrl: "/guessmaster/images/aktor/aktor_rizky-febian.jpg" },
    { name: "roy marten", imageUrl: "/guessmaster/images/aktor/aktor_roy-marten.jpg" },
    { name: "ruben onsu", imageUrl: "/guessmaster/images/aktor/aktor_ruben-onsu.jpg" },
    { name: "tora sudiro", imageUrl: "/guessmaster/images/aktor/aktor_tora-sudiro.jpg" },
    { name: "tukul arwana", imageUrl: "/guessmaster/images/aktor/aktor_tukul-arwana.jpg" },
    { name: "uus", imageUrl: "/guessmaster/images/aktor/aktor_uus.jpg" },
    { name: "vicky nitinegoro", imageUrl: "/guessmaster/images/aktor/aktor_vicky-nitinegoro.jpg" },
    { name: "vicky prasetyo", imageUrl: "/guessmaster/images/aktor/aktor_vicky-prasetyo.jpg" },
  ],
  pokemon:[
    { name: "cinderace", imageUrl: "/guessmaster/images/pokemon/pokemon_cinderace.jpg" },
    { name: "gengar", imageUrl: "/guessmaster/images/pokemon/pokemon_gengar.jpg" },
    { name: "lucario", imageUrl: "/guessmaster/images/pokemon/pokemon_lucario.jpg" },
    { name: "lugia", imageUrl: "/guessmaster/images/pokemon/pokemon_lugia.jpg" },
    { name: "mewtwo", imageUrl: "/guessmaster/images/pokemon/pokemon_mewtwo.jpg" },
    { name: "palkia", imageUrl: "/guessmaster/images/pokemon/pokemon_palkia.jpg" },
    { name: "pikachu", imageUrl: "/guessmaster/images/pokemon/pokemon_pikachu.jpg" },
    { name: "zacian", imageUrl: "/guessmaster/images/pokemon/pokemon_zacian.jpg" },
    { name: "zapdos", imageUrl: "/guessmaster/images/pokemon/pokemon_zapdos.jpg" },
    { name: "zekrom", imageUrl: "/guessmaster/images/pokemon/pokemon_zekrom.jpg" },
    { name: "absol", imageUrl: "/guessmaster/images/pokemon/pokemon_Absol.jpg" },
    { name: "aegislash", imageUrl: "/guessmaster/images/pokemon/pokemon_Aegislash.jpg" },
    { name: "amoonguss", imageUrl: "/guessmaster/images/pokemon/pokemon_Amoonguss.jpg" },
    { name: "avalugg", imageUrl: "/guessmaster/images/pokemon/pokemon_Avalugg.jpg" },
    { name: "barboach", imageUrl: "/guessmaster/images/pokemon/pokemon_Barboach.jpg" },
    { name: "bergmite", imageUrl: "/guessmaster/images/pokemon/pokemon_Bergmite.jpg" },
    { name: "blastoise", imageUrl: "/guessmaster/images/pokemon/pokemon_Blastoise.jpg" },
    { name: "blissey", imageUrl: "/guessmaster/images/pokemon/pokemon_Blissey.jpg" },
    { name: "bulbasaur", imageUrl: "/guessmaster/images/pokemon/pokemon_Bulbasaur.jpg" },
    { name: "cacnea", imageUrl: "/guessmaster/images/pokemon/pokemon_Cacnea.jpg" },
    { name: "calytex", imageUrl: "/guessmaster/images/pokemon/pokemon_Calyrex.jpg" },
    { name: "caterpie", imageUrl: "/guessmaster/images/pokemon/pokemon_Caterpie.jpg" },
    { name: "charizard", imageUrl: "/guessmaster/images/pokemon/pokemon_Charizard.jpg" },
    { name: "charmander", imageUrl: "/guessmaster/images/pokemon/pokemon_Charmander.jpg" },
    { name: "clefairy", imageUrl: "/guessmaster/images/pokemon/pokemon_Clefairy.jpg" },
    { name: "cramorant", imageUrl: "/guessmaster/images/pokemon/pokemon_Cramorant.jpg" },
    { name: "delphox", imageUrl: "/guessmaster/images/pokemon/pokemon_Delphox.jpg" },
    { name: "ditto", imageUrl: "/guessmaster/images/pokemon/pokemon_Ditto.jpg" },
    { name: "dragonite", imageUrl: "/guessmaster/images/pokemon/pokemon_Dragonite.jpg" },
    { name: "drifloon", imageUrl: "/guessmaster/images/pokemon/pokemon_Drifloon.jpg" },
    { name: "ducklett", imageUrl: "/guessmaster/images/pokemon/pokemon_Ducklett.jpg" },
    { name: "feebas", imageUrl: "/guessmaster/images/pokemon/pokemon_Feebas.jpg" },
    { name: "ferrothorn", imageUrl: "/guessmaster/images/pokemon/pokemon_Ferrothorn.jpg" },
    { name: "flaaffy", imageUrl: "/guessmaster/images/pokemon/pokemon_Flaaffy.jpg" },
    { name: "flabebe", imageUrl: "/guessmaster/images/pokemon/pokemon_Flabébé.jpg" },
    { name: "fomantis", imageUrl: "/guessmaster/images/pokemon/pokemon_Fomantis.jpg" },
    { name: "gardevoir", imageUrl: "/guessmaster/images/pokemon/pokemon_Gardevoir.jpg" },
    { name: "geodude", imageUrl: "/guessmaster/images/pokemon/pokemon_Geodude.jpg" },
    { name: "giratina", imageUrl: "/guessmaster/images/pokemon/pokemon_Giratina.jpg" },
    { name: "gligar", imageUrl: "/guessmaster/images/pokemon/pokemon_Gligar.jpg" },
    { name: "golett", imageUrl: "/guessmaster/images/pokemon/pokemon_Golett.jpg" },
    { name: "ho-oh", imageUrl: "/guessmaster/images/pokemon/pokemon_Ho-oh.jpg.jpg" },
    { name: "hoopa", imageUrl: "/guessmaster/images/pokemon/pokemon_Hoopa.jpg" },
    { name: "hoppip", imageUrl: "/guessmaster/images/pokemon/pokemon_Hoppip.jpg" },
    { name: "incineroar", imageUrl: "/guessmaster/images/pokemon/pokemon_Incineroar.jpg" },
    { name: "ivysaur", imageUrl: "/guessmaster/images/pokemon/pokemon_Ivysaur.jpg" },
    { name: "krokorok", imageUrl: "/guessmaster/images/pokemon/pokemon_Krokorok.jpg" },
    { name: "kyogre", imageUrl: "/guessmaster/images/pokemon/pokemon_Kyogre.jpg" },
    { name: "lairon", imageUrl: "/guessmaster/images/pokemon/pokemon_Lairon.jpg" },
    { name: "landorus", imageUrl: "/guessmaster/images/pokemon/pokemon_Landorus.jpg" },
    { name: "ledyba", imageUrl: "/guessmaster/images/pokemon/pokemon_Ledyba.jpg" },
    { name: "lotad", imageUrl: "/guessmaster/images/pokemon/pokemon_Lotad.jpg" },
    { name: "machamp", imageUrl: "/guessmaster/images/pokemon/pokemon_Machamp.jpg" },
    { name: "magnemite", imageUrl: "/guessmaster/images/pokemon/pokemon_Magnemite.jpg" },
    { name: "makuhita", imageUrl: "/guessmaster/images/pokemon/pokemon_Makuhita.jpg" },
    { name: "manectric", imageUrl: "/guessmaster/images/pokemon/pokemon_Manectric.jpg" },
    { name: "mega manectric", imageUrl: "/guessmaster/images/pokemon/pokemon_Manectric.jpg" },
    { name: "mienfoo", imageUrl: "/guessmaster/images/pokemon/pokemon_Mienfoo.jpg" },
    { name: "munna", imageUrl: "/guessmaster/images/pokemon/pokemon_Munna.jpg" },
    { name: "nidorina", imageUrl: "/guessmaster/images/pokemon/pokemon_Nidorina.jpg" },
    { name: "ninetales", imageUrl: "/guessmaster/images/pokemon/pokemon_ninetales.jpg" },
    { name: "oddish", imageUrl: "/guessmaster/images/pokemon/pokemon_Oddish.jpg" },
    { name: "oshawott", imageUrl: "/guessmaster/images/pokemon/pokemon_Oshawott.jpg" },
    { name: "phanpy", imageUrl: "/guessmaster/images/pokemon/pokemon_Phanpy.jpg" },
    { name: "pidgey", imageUrl: "/guessmaster/images/pokemon/pokemon_Pidgey.jpg" },
    { name: "pignite", imageUrl: "/guessmaster/images/pokemon/pokemon_Pignite.jpg" },
    { name: "piloswine", imageUrl: "/guessmaster/images/pokemon/pokemon_Piloswine.jpg" },
    { name: "poliwag", imageUrl: "/guessmaster/images/pokemon/pokemon_Poliwag.jpg" },
    { name: "porygon2", imageUrl: "/guessmaster/images/pokemon/pokemon_Porygon2.jpg" },
    { name: "pumpkaboo", imageUrl: "/guessmaster/images/pokemon/pokemon_Pumpkaboo.jpg" },
    { name: "purrloin", imageUrl: "/guessmaster/images/pokemon/pokemon_Purrloin.jpg" },
    { name: "quagsire", imageUrl: "/guessmaster/images/pokemon/pokemon_Quagsire.jpg" },
    { name: "rattata", imageUrl: "/guessmaster/images/pokemon/pokemon_Rattata.jpg" },
    { name: "sandygast", imageUrl: "/guessmaster/images/pokemon/pokemon_Sandygast.jpg" },
    { name: "seadra", imageUrl: "/guessmaster/images/pokemon/pokemon_Seadra.jpg" },
    { name: "seedot", imageUrl: "/guessmaster/images/pokemon/pokemon_Seedot.jpg" },
    { name: "seel", imageUrl: "/guessmaster/images/pokemon/pokemon_Seel.jpg" },
    { name: "shellder", imageUrl: "/guessmaster/images/pokemon/pokemon_Shellder.jpg" },
    { name: "slowbro", imageUrl: "/guessmaster/images/pokemon/pokemon_Slowbro.jpg" },
    { name: "snorlax", imageUrl: "/guessmaster/images/pokemon/pokemon_Snorlax.jpg" },
    { name: "squirtle", imageUrl: "/guessmaster/images/pokemon/pokemon_Squirtle.jpg" },
    { name: "stantler", imageUrl: "/guessmaster/images/pokemon/pokemon_Stantler.jpg" },
    { name: "staryu", imageUrl: "/guessmaster/images/pokemon/pokemon_Staryu.jpg" },
    { name: "taillow", imageUrl: "/guessmaster/images/pokemon/pokemon_Taillow.jpg" },
    { name: "talonflame", imageUrl: "/guessmaster/images/pokemon/pokemon_Talonflame.jpg" },
    { name: "tepig", imageUrl: "/guessmaster/images/pokemon/pokemon_Tepig.jpg" },
    { name: "tirtouga", imageUrl: "/guessmaster/images/pokemon/pokemon_Tirtouga.jpg" },
    { name: "trapinch", imageUrl: "/guessmaster/images/pokemon/pokemon_Trapinch.jpg" },
    { name: "tympole", imageUrl: "/guessmaster/images/pokemon/pokemon_Tympole.jpg" },
    { name: "tyranitar", imageUrl: "/guessmaster/images/pokemon/pokemon_Tyranitar.jpg" },
    { name: "venonat", imageUrl: "/guessmaster/images/pokemon/pokemon_Venonat.jpg" },
    { name: "venusaur", imageUrl: "/guessmaster/images/pokemon/pokemon_Venusaur.jpg" },
    { name: "vibrava", imageUrl: "/guessmaster/images/pokemon/pokemon_Vibrava.jpg" },
    { name: "vivilion", imageUrl: "/guessmaster/images/pokemon/pokemon_Vivillon.jpg" },
    { name: "wingull", imageUrl: "/guessmaster/images/pokemon/pokemon_Wingull.jpg" },
    { name: "wooper", imageUrl: "/guessmaster/images/pokemon/pokemon_Wooper.jpg" },
    { name: "wurmple", imageUrl: "/guessmaster/images/pokemon/pokemon_Wurmple.jpg" },
    { name: "yanma", imageUrl: "/guessmaster/images/pokemon/pokemon_Yanma.jpg" },
    { name: "yveltal", imageUrl: "/guessmaster/images/pokemon/pokemon_Yanma.jpg" },
    { name: "zigzagoon", imageUrl: "/guessmaster/images/pokemon/pokemon_Zigzagoon.jpg" },
  ],
  waifu:[
    { name: "amellia watson", imageUrl: "/guessmaster/images/waifu/waifu_amellia-watson.jpg" },
    { name: "gawr gura", imageUrl: "/guessmaster/images/waifu/waifu_gawr-gura.jpg" },
    { name: "hitagi senjougahara", imageUrl: "/guessmaster/images/waifu/waifu_hitagi-senjougahara.jpg" },
    { name: "kiryu coco", imageUrl: "/guessmaster/images/waifu/waifu_kiryu-coco.jpg" },
    { name: "mori calliope", imageUrl: "/guessmaster/images/waifu/waifu_mori-calliope.jpg" },
    { name: "ninomae ina'nis", imageUrl: "/guessmaster/images/waifu/waifu_ninomae-ina'nis.jpg" },
    { name: "shinobu oshino", imageUrl: "/guessmaster/images/waifu/waifu_shinobu-oshino.jpg" },
    { name: "shirakami fubuki", imageUrl: "/guessmaster/images/waifu/waifu_shirakami-fubuki.jpg" },
    { name: "takanashi kiara", imageUrl: "/guessmaster/images/waifu/waifu_takanashi-kiara.jpg" },
    { name: "tsubasa hanekawa", imageUrl: "/guessmaster/images/waifu/waifu_tsubasa-hanekawa.jpg" },
    { name: "ai hayasaka", imageUrl: "/guessmaster/images/waifu/waifu_Ai-Hayasaka.jpg" },
    { name: "ai ohto", imageUrl: "/guessmaster/images/waifu/waifu_Ai-Ohto.jpg" },
    { name: "akame", imageUrl: "/guessmaster/images/waifu/waifu_Akame.jpg" },
    { name: "akeno himejima", imageUrl: "/guessmaster/images/waifu/waifu_Akeno-Himejima.jpg" },
    { name: "albedo", imageUrl: "/guessmaster/images/waifu/waifu_Albedo.jpg" },
    { name: "alice", imageUrl: "/guessmaster/images/waifu/waifu_Alice-Synthesis-Thirty.jpg" },
    { name: "annie", imageUrl: "/guessmaster/images/waifu/waifu_Annie-Leonhart.jpg" },
    { name: "aqua", imageUrl: "/guessmaster/images/waifu/waifu_Aqua.jpg" },
    { name: "saber alter", imageUrl: "/guessmaster/images/waifu/waifu_Artoria-Pendragon-Alter.jpg" },
    { name: "asuka", imageUrl: "/guessmaster/images/waifu/waifu_Asuka-Langley-Soryu.jpg" },
    { name: "asuna", imageUrl: "/guessmaster/images/waifu/waifu_Asuna.jpg" },
    { name: "ayunda risu", imageUrl: "/guessmaster/images/waifu/waifu_Ayunda-Risu.jpg" },
    { name: "boa hancock", imageUrl: "/guessmaster/images/waifu/waifu_Boa-Hancock.jpg" },
    { name: "c.c", imageUrl: "/guessmaster/images/waifu/waifu_cc.jpg" },
    { name: "chiaki nanami", imageUrl: "/guessmaster/images/waifu/waifu_Chiaki-Nanami.jpg" },
    { name: "chika fujiwara", imageUrl: "/guessmaster/images/waifu/waifu_Chika-Fujiwara.jpg" },
    { name: "chizuru", imageUrl: "/guessmaster/images/waifu/waifu_Chizuru-Ichinose.jpg" },
    { name: "crona", imageUrl: "/guessmaster/images/waifu/waifu_Crona.jpg" },
    { name: "darkness", imageUrl: "/guessmaster/images/waifu/waifu_Darkness.jpg" },
    { name: "echidna", imageUrl: "/guessmaster/images/waifu/waifu_Echidna.jpg" },
    { name: "emilia", imageUrl: "/guessmaster/images/waifu/waifu_Emilia.jpg" },
    { name: "erina nakiri", imageUrl: "/guessmaster/images/waifu/waifu_Erina-Nakiri.jpg" },
    { name: "erza scarlet", imageUrl: "/guessmaster/images/waifu/waifu_Erza-Scarlet.jpg" },
    { name: "esdeath", imageUrl: "/guessmaster/images/waifu/waifu_Esdeath.jpg" },
    { name: "fubuki", imageUrl: "/guessmaster/images/waifu/waifu_Fubuki.jpg" },
    { name: "hange", imageUrl: "/guessmaster/images/waifu/waifu_Hange-Zoë.jpg" },
    { name: "hatsune miku", imageUrl: "/guessmaster/images/waifu/waifu_Hatsune-Miku.jpg" },
    { name: "hestia", imageUrl: "/guessmaster/images/waifu/waifu_Hestia.jpg" },
    { name: "himiko toga", imageUrl: "/guessmaster/images/waifu/waifu_Himiko-Toga.jpg" },
    { name: "hinata hyuuga", imageUrl: "/guessmaster/images/waifu/waifu_Hinata-Hyuuga.jpg" },
    { name: "ichika nakano", imageUrl: "/guessmaster/images/waifu/waifu_Ichika-Nakano.jpg" },
    { name: "inugami korone", imageUrl: "/guessmaster/images/waifu/waifu_Inugami-Korone.jpg" },
    { name: "itsuki nakano", imageUrl: "/guessmaster/images/waifu/waifu_Itsuki-Nakano.jpg" },
    { name: "jolyne cujoh", imageUrl: "/guessmaster/images/waifu/waifu_Jolyne-Cujoh.jpg" },
    { name: "junko", imageUrl: "/guessmaster/images/waifu/waifu_Junko Enoshima.jpg" },
    { name: "kaguya shinomiya", imageUrl: "/guessmaster/images/waifu/waifu_Kaguya-Shinomiya.jpg" },
    { name: "kanao tsuyuri", imageUrl: "/guessmaster/images/waifu/waifu_Kanao-Tsuyuri.jpg" },
    { name: "kanna kamui", imageUrl: "/guessmaster/images/waifu/waifu_Kanna-Kamui.jpg" },
    { name: "kaori miyazono", imageUrl: "/guessmaster/images/waifu/waifu_Kaori-Miyazono.jpg" },
    { name: "komi shouko", imageUrl: "/guessmaster/images/waifu/waifu_Komi-Shouko.jpg" },
    { name: "krista", imageUrl: "/guessmaster/images/waifu/waifu_Krista-Lenz.jpg" },
    { name: "kurisu makise", imageUrl: "/guessmaster/images/waifu/waifu_Kurisu-Makise.jpg" },
    { name: "kurumi tokisaki", imageUrl: "/guessmaster/images/waifu/waifu_Kurumi-Tokisaki.jpg" },
    { name: "kyoko kirigiri", imageUrl: "/guessmaster/images/waifu/waifu_Kyoko-Kirigiri.jpg" },
    { name: "kyouka jirou", imageUrl: "/guessmaster/images/waifu/waifu_Kyouka-Jirou.jpg" },
    { name: "hori", imageUrl: "/guessmaster/images/waifu/waifu_Kyouko-Hori.jpg" },
    { name: "lucoa", imageUrl: "/guessmaster/images/waifu/waifu_Lucoa.jpg" },
    { name: "lucy", imageUrl: "/guessmaster/images/waifu/waifu_Lucy-Heartfilia.jpg" },
    { name: "mai sakurajima", imageUrl: "/guessmaster/images/waifu/waifu_Mai-Sakurajima.jpg" },
    { name: "makima", imageUrl: "/guessmaster/images/waifu/waifu_Makima.jpg" },
    { name: "maki zennin", imageUrl: "/guessmaster/images/waifu/waifu_Maki-Zenin.jpg" },
    { name: "marin kitagawa", imageUrl: "/guessmaster/images/waifu/waifu_Marin-Kitagawa.jpg" },
    { name: "mary sotome", imageUrl: "/guessmaster/images/waifu/waifu_Mary-Saotome .jpg" },
    { name: "megumin", imageUrl: "/guessmaster/images/waifu/waifu_Megumin.jpg" },
    { name: "mikasa ackerman", imageUrl: "/guessmaster/images/waifu/waifu_Mikasa-Ackerman.jpg" },
    { name: "miku nakano", imageUrl: "/guessmaster/images/waifu/waifu_Miku-Nakano.jpg" },
    { name: "miruko", imageUrl: "/guessmaster/images/waifu/waifu_Miruko.jpg" },
    { name: "misa amane", imageUrl: "/guessmaster/images/waifu/waifu_Misa-Amane.jpg" },
    { name: "misato katsuragi", imageUrl: "/guessmaster/images/waifu/waifu_Misato-Katsuragi.jpg" },
    { name: "mitsuri kanroji", imageUrl: "/guessmaster/images/waifu/waifu_Mitsuri-Kanroji.jpg" },
    { name: "momo yaoyorozu", imageUrl: "/guessmaster/images/waifu/waifu_Momo-Yaoyorozu.jpg" },
    { name: "nagatoro", imageUrl: "/guessmaster/images/waifu/waifu_Nagatoro-san.jpg" },
    { name: "nami", imageUrl: "/guessmaster/images/waifu/waifu_Nami.jpg" },
    { name: "nanika", imageUrl: "/guessmaster/images/waifu/waifu_Nanika.jpg" },
    { name: "neferpitou", imageUrl: "/guessmaster/images/waifu/waifu_Neferpitou.jpg" },
    { name: "nekomata okayu", imageUrl: "/guessmaster/images/waifu/waifu_Nekomata-Okayu.jpg" },
    { name: "nezuko", imageUrl: "/guessmaster/images/waifu/waifu_Nezuko.jpg" },
    { name: "nico robin", imageUrl: "/guessmaster/images/waifu/waifu_Nico-Robin.jpg" },
    { name: "nino nakano", imageUrl: "/guessmaster/images/waifu/waifu_Nino-Nakano.jpg" },
    { name: "nobara", imageUrl: "/guessmaster/images/waifu/waifu_Nobara-Kugisaki.jpg" },
    { name: "ochako uraraka", imageUrl: "/guessmaster/images/waifu/waifu_Ochako-Uraraka.jpg" },
    { name: "power", imageUrl: "/guessmaster/images/waifu/waifu_Power.jpg" },
    { name: "ram", imageUrl: "/guessmaster/images/waifu/waifu_ram.jpg" },
    { name: "raphtalia", imageUrl: "/guessmaster/images/waifu/waifu_Raphtalia.jpg" },
    { name: "rei ayanami", imageUrl: "/guessmaster/images/waifu/waifu_Rei-Ayanami.jpg" },
    { name: "rem", imageUrl: "/guessmaster/images/waifu/waifu_rem.jpg" },
    { name: "rias gremory", imageUrl: "/guessmaster/images/waifu/waifu_Rias-Gremory.jpg" },
    { name: "rikka takanashi", imageUrl: "/guessmaster/images/waifu/waifu_Rikka-Takanashi.jpg" },
    { name: "rin tohsaka", imageUrl: "/guessmaster/images/waifu/waifu_Rin-Tohsaka.jpg" },
    { name: "rio futaba", imageUrl: "/guessmaster/images/waifu/waifu_Rio-Futaba.jpg" },
    { name: "ryuuko matori", imageUrl: "/guessmaster/images/waifu/waifu_Ryuuko-Matoi.jpg" },
    { name: "saber", imageUrl: "/guessmaster/images/waifu/waifu_Saber.jpg" },
    { name: "sasha braus", imageUrl: "/guessmaster/images/waifu/waifu_Sasha-Braus.jpg" },
    { name: "shinobu kochou", imageUrl: "/guessmaster/images/waifu/waifu_Shinobu-Kochou.jpg" },
    { name: "shiro", imageUrl: "/guessmaster/images/waifu/waifu_Shiro.jpg" },
    { name: "shouko nishimiya", imageUrl: "/guessmaster/images/waifu/waifu_Shouko-Nishimiya.jpg" },
    { name: "sinon", imageUrl: "/guessmaster/images/waifu/waifu_Sinon.jpg" },
    { name: "taiga aisaka", imageUrl: "/guessmaster/images/waifu/waifu_Taiga-Aisaka.jpg" },
    { name: "tatsumaki", imageUrl: "/guessmaster/images/waifu/waifu_Tatsumaki.jpg" },
    { name: "tohru", imageUrl: "/guessmaster/images/waifu/waifu_Tohru.jpg" },
    { name: "touka", imageUrl: "/guessmaster/images/waifu/waifu_Touka-Kirishima.jpg" },
    { name: "tsunade", imageUrl: "/guessmaster/images/waifu/waifu_Tsunade.jpg" },
    { name: "tsuyu asui", imageUrl: "/guessmaster/images/waifu/waifu_Tsuyu-Asui.jpg" },
    { name: "violet evergarden", imageUrl: "/guessmaster/images/waifu/waifu_Violet-Evergarden.jpg" },
    { name: "yor forger", imageUrl: "/guessmaster/images/waifu/waifu_Yor-Forger.jpg" },
    { name: "yotsuba nakano", imageUrl: "/guessmaster/images/waifu/waifu_Yotsuba-Nakano.jpg" },
    { name: "yukino", imageUrl: "/guessmaster/images/waifu/waifu_Yukino-Yukinoshita.jpg" },
    { name: "yumeko jabami", imageUrl: "/guessmaster/images/waifu/waifu_Yumeko-Jabami.jpg" },
    { name: "yuno gasai", imageUrl: "/guessmaster/images/waifu/waifu_Yuno-Gasai .jpg" },
    { name: "zero two", imageUrl: "/guessmaster/images/waifu/waifu_zero-two.jpg" },
  ],
  city:[
    { name: "aceh", imageUrl: "/guessmaster/images/kota/city_Aceh.jpg" },
    { name: "ambon", imageUrl: "/guessmaster/images/kota/city_Ambon.jpg" },
    { name: "bali", imageUrl: "/guessmaster/images/kota/city_Bali.jpg" },
    { name: "balikpapan", imageUrl: "/guessmaster/images/kota/city_Balikpapan.jpg" },
    { name: "banda aceh", imageUrl: "/guessmaster/images/kota/city_Banda-Aceh.jpg" },
    { name: "bandar lampung", imageUrl: "/guessmaster/images/kota/city_Bandar-Lampung.jpg" },
    { name: "bandung", imageUrl: "/guessmaster/images/kota/city_Bandung.jpg" },
    { name: "banjar", imageUrl: "/guessmaster/images/kota/city_Banjar.jpg" },
    { name: "banjarbaru", imageUrl: "/guessmaster/images/kota/city_Banjarbaru.jpg" },
    { name: "banjarmasin", imageUrl: "/guessmaster/images/kota/city_Banjarmasin.jpg" },
    { name: "batam", imageUrl: "/guessmaster/images/kota/city_Batam.jpg" },
    { name: "batu", imageUrl: "/guessmaster/images/kota/city_Batu.jpg" },
    { name: "baubau", imageUrl: "/guessmaster/images/kota/city_Baubau.jpg" },
    { name: "bekasi", imageUrl: "/guessmaster/images/kota/city_Bekasi.jpg" },
    { name: "bengkulu", imageUrl: "/guessmaster/images/kota/city_Bengkulu.jpg" },
    { name: "bima", imageUrl: "/guessmaster/images/kota/city_Bima.jpg" },
    { name: "binjai", imageUrl: "/guessmaster/images/kota/city_Binjai.jpg" },
    { name: "bitung", imageUrl: "/guessmaster/images/kota/city_Bitung.jpg" },
    { name: "blitar", imageUrl: "/guessmaster/images/kota/city_Blitar.jpg" },
    { name: "bogor", imageUrl: "/guessmaster/images/kota/city_Bogor.jpg" },
    { name: "bontang", imageUrl: "/guessmaster/images/kota/city_Bontang.jpg" },
    { name: "bukittinggi", imageUrl: "/guessmaster/images/kota/city_Bukittinggi.jpg" },
    { name: "cilegon", imageUrl: "/guessmaster/images/kota/city_Cilegon.jpg" },
    { name: "cimahi", imageUrl: "/guessmaster/images/kota/city_Cimahi.jpg" },
    { name: "cirebon", imageUrl: "/guessmaster/images/kota/city_Cirebon.jpg" },
    { name: "depok", imageUrl: "/guessmaster/images/kota/city_Depok.jpg" },
    { name: "dumai", imageUrl: "/guessmaster/images/kota/city_Dumai.jpg" },
    { name: "gorontalo", imageUrl: "/guessmaster/images/kota/city_Gorontalo.jpg" },
    { name: "gunungsitoli", imageUrl: "/guessmaster/images/kota/city_Gunungsitoli.jpg" },
    { name: "jakarta", imageUrl: "/guessmaster/images/kota/city_Jakarta.jpg" },
    { name: "jakrta barat", imageUrl: "/guessmaster/images/kota/city_Jakarta-Barat.jpg" },
    { name: "jakarta pusat", imageUrl: "/guessmaster/images/kota/city_Jakarta-Pusat.jpg" },
    { name: "jakarta selatan", imageUrl: "/guessmaster/images/kota/city_Jakarta-Selatan.jpg" },
    { name: "jakarta timur", imageUrl: "/guessmaster/images/kota/city_Jakarta-Timur.jpg" },
    { name: "jakarta utara", imageUrl: "/guessmaster/images/kota/city_Jakarta-Utara.jpg" },
    { name: "jambi", imageUrl: "/guessmaster/images/kota/city_Jambi.jpg" },
    { name: "jayapura", imageUrl: "/guessmaster/images/kota/city_Jayapura.jpg" },
    { name: "kediri", imageUrl: "/guessmaster/images/kota/city_Kediri.jpg" },
    { name: "kendari", imageUrl: "/guessmaster/images/kota/city_Kendari.jpg" },
    { name: "kotamobagu", imageUrl: "/guessmaster/images/kota/city_Kotamobagu.jpg" },
    { name: "kupang", imageUrl: "/guessmaster/images/kota/city_Kupang.jpg" },
    { name: "lampung selatan", imageUrl: "/guessmaster/images/kota/city_Lampung-Selatan.jpg" },
    { name: "langsa", imageUrl: "/guessmaster/images/kota/city_Langsa.jpg" },
    { name: "lhokseumawe", imageUrl: "/guessmaster/images/kota/city_Lhokseumawe.jpg" },
    { name: "lubuklinggau", imageUrl: "/guessmaster/images/kota/city_Lubuklinggau.jpg" },
    { name: "madiun", imageUrl: "/guessmaster/images/kota/city_Madiun.jpg" },
    { name: "magelang", imageUrl: "/guessmaster/images/kota/city_Magelang.jpg" },
    { name: "makssar", imageUrl: "/guessmaster/images/kota/city_Makassar.jpg" },
    { name: "malang", imageUrl: "/guessmaster/images/kota/city_Malang.jpg" },
    { name: "manado", imageUrl: "/guessmaster/images/kota/city_Manado.jpg" },
    { name: "mataram", imageUrl: "/guessmaster/images/kota/city_Mataram.jpg" },
    { name: "medan", imageUrl: "/guessmaster/images/kota/city_Medan.jpg" },
    { name: "metro", imageUrl: "/guessmaster/images/kota/city_Metro.jpg" },
    { name: "mojokerto", imageUrl: "/guessmaster/images/kota/city_Mojokerto.jpg" },
    { name: "padang", imageUrl: "/guessmaster/images/kota/city_Padang.jpg" },
    { name: "padang panjang", imageUrl: "/guessmaster/images/kota/city_Padang-Panjang.jpg" },
    { name: "padang sidempuan", imageUrl: "/guessmaster/images/kota/city_Padang-Sidempuan.jpg" },
    { name: "pagar alam", imageUrl: "/guessmaster/images/kota/city_Pagar-Alam.jpg" },
    { name: "palangka raya", imageUrl: "/guessmaster/images/kota/city_Pagar-Alam.jpg" },
    { name: "palembang", imageUrl: "/guessmaster/images/kota/city_Palembang.jpg" },
    { name: "palopo", imageUrl: "/guessmaster/images/kota/city_Palopo.jpg" },
    { name: "palu", imageUrl: "/guessmaster/images/kota/city_Palu.jpg" },
    { name: "pangkalpinang", imageUrl: "/guessmaster/images/kota/city_Pangkalpinang.jpg" },
    { name: "parepare", imageUrl: "/guessmaster/images/kota/city_Parepare.jpg" },
    { name: "pariaman", imageUrl: "/guessmaster/images/kota/city_Pariaman.jpg" },
    { name: "pasuruan", imageUrl: "/guessmaster/images/kota/city_Pasuruan.jpg" },
    { name: "payakumbuh", imageUrl: "/guessmaster/images/kota/city_Payakumbuh.jpg" },
    { name: "pekalongan", imageUrl: "/guessmaster/images/kota/city_Pekalongan.jpg" },
    { name: "pekanbaru", imageUrl: "/guessmaster/images/kota/city_Pekanbaru.jpg" },
    { name: "pematangsiantar", imageUrl: "/guessmaster/images/kota/city_Pematangsiantar.jpg" },
    { name: "pontianak", imageUrl: "/guessmaster/images/kota/city_Pontianak.jpg" },
    { name: "prabumulih", imageUrl: "/guessmaster/images/kota/city_Prabumulih.jpg" },
    { name: "probolinggo", imageUrl: "/guessmaster/images/kota/city_Probolinggo.jpg" },
    { name: "sabang", imageUrl: "/guessmaster/images/kota/city_Sabang.jpg" },
    { name: "salatiga", imageUrl: "/guessmaster/images/kota/city_Salatiga.jpg" },
    { name: "samarinda", imageUrl: "/guessmaster/images/kota/city_Samarinda.jpg" },
    { name: "sawahlunto", imageUrl: "/guessmaster/images/kota/city_Sawahlunto.jpg" },
    { name: "semarang", imageUrl: "/guessmaster/images/kota/city_Semarang.jpg" },
    { name: "serang", imageUrl: "/guessmaster/images/kota/city_Serang.jpg" },
    { name: "sibolga", imageUrl: "/guessmaster/images/kota/city_Sibolga.jpg" },
    { name: "singkawang", imageUrl: "/guessmaster/images/kota/city_Singkawang.jpg" },
    { name: "sleman", imageUrl: "/guessmaster/images/kota/city_Sleman.jpg" },
    { name: "solok", imageUrl: "/guessmaster/images/kota/city_Solok.jpg" },
    { name: "sorong", imageUrl: "/guessmaster/images/kota/city_Sorong.jpg" },
    { name: "sabulussalam", imageUrl: "/guessmaster/images/kota/city_Subulussalam.jpg" },
    { name: "sukabumi", imageUrl: "/guessmaster/images/kota/city_Sukabumi.jpg" },
    { name: "sungai penuh", imageUrl: "/guessmaster/images/kota/city_Sungai-Penuh.jpg" },
    { name: "surabaya", imageUrl: "/guessmaster/images/kota/city_Surabaya.jpg" },
    { name: "surakarta", imageUrl: "/guessmaster/images/kota/city_Surakarta.jpg" },
    { name: "tana toraja", imageUrl: "/guessmaster/images/kota/city_Tana-Toraja.jpg" },
    { name: "tanggerang", imageUrl: "/guessmaster/images/kota/city_Tangerang.jpg" },
    { name: "tanggerang selatan", imageUrl: "/guessmaster/images/kota/city_Tangerang-Selatan.jpg" },
    { name: "tanjungbalai", imageUrl: "/guessmaster/images/kota/city_Tanjungbalai.jpg" },
    { name: "tanjungpinang", imageUrl: "/guessmaster/images/kota/city_Tanjungpinang.jpg" },
    { name: "tarakan", imageUrl: "/guessmaster/images/kota/city_Tarakanjpg" },
    { name: "tasikmalaya", imageUrl: "/guessmaster/images/kota/city_Tasikmalaya.jpg" },
    { name: "tebing tinggi", imageUrl: "/guessmaster/images/kota/city_Tebing-Tinggi.jpg" },
    { name: "tegal", imageUrl: "/guessmaster/images/kota/city_Tegal.jpg" },
    { name: "ternate", imageUrl: "/guessmaster/images/kota/city_Ternate.jpg" },
    { name: "yogyakarta", imageUrl: "/guessmaster/images/kota/city_Yogyakarta.jpg" },
  ],
  flag:[
    { name: "afganistan", imageUrl: "/guessmaster/images/bendera/bendera_Afganistan.png" },
    { name: "afrika selatan", imageUrl: "/guessmaster/images/bendera/bendera_Afrika-Selatan.png" },
    { name: "albania", imageUrl: "/guessmaster/images/bendera/bendera_Albania.png" },
    { name: "aljazair", imageUrl: "/guessmaster/images/bendera/bendera_Aljazair.png" },
    { name: "amerika serikat", imageUrl: "/guessmaster/images/bendera/bendera_Amerika-Serikat.png" },
    { name: "andorra", imageUrl: "/guessmaster/images/bendera/bendera_Andorra.png" },
    { name: "angola", imageUrl: "/guessmaster/images/bendera/bendera_Angola.png" },
    { name: "antigua", imageUrl: "/guessmaster/images/bendera/bendera_Antigua-dan-Barbuda.png" },
    { name: "arab saudi", imageUrl: "/guessmaster/images/bendera/bendera_Arab-Saudi.png" },
    { name: "argentina", imageUrl: "/guessmaster/images/bendera/bendera_Argentina.png" },
    { name: "armenia", imageUrl: "/guessmaster/images/bendera/bendera_Armenia.png" },
    { name: "australia", imageUrl: "/guessmaster/images/bendera/bendera_Australia.png" },
    { name: "austria", imageUrl: "/guessmaster/images/bendera/bendera_Austria.png" },
    { name: "azerbaijan", imageUrl: "/guessmaster/images/bendera/bendera_Azerbaijan.png" },
    { name: "bahama", imageUrl: "/guessmaster/images/bendera/bendera_Bahama.png" },
    { name: "bahrain", imageUrl: "/guessmaster/images/bendera/bendera_Bahrain.png" },
    { name: "bangladesh", imageUrl: "/guessmaster/images/bendera/bendera_Bangladesh.png" },
    { name: "bardos", imageUrl: "/guessmaster/images/bendera/bendera_Barbados.png" },
    { name: "belanda", imageUrl: "/guessmaster/images/bendera/bendera_Belanda.png" },
    { name: "belarus", imageUrl: "/guessmaster/images/bendera/bendera_Belarus.png" },
    { name: "belgia", imageUrl: "/guessmaster/images/bendera/bendera_Belgia.png" },
    { name: "belize", imageUrl: "/guessmaster/images/bendera/bendera_Belize.png" },
    { name: "benin", imageUrl: "/guessmaster/images/bendera/bendera_Benin.png" },
    { name: "bhutan", imageUrl: "/guessmaster/images/bendera/bendera_Bhutan.png" },
    { name: "bolivia", imageUrl: "/guessmaster/images/bendera/bendera_Bolivia.png" },
    { name: "bosnia", imageUrl: "/guessmaster/images/bendera/bendera_Bosnia-dan-Herzegovina.png" },
    { name: "bostwana", imageUrl: "/guessmaster/images/bendera/bendera_Botswana.png" },
    { name: "brasil", imageUrl: "/guessmaster/images/bendera/bendera_Brasil.png" },
    { name: "brunei", imageUrl: "/guessmaster/images/bendera/bendera_Brunei.png" },
    { name: "bulgaria", imageUrl: "/guessmaster/images/bendera/bendera_Bulgaria.png" },
    { name: "brukina faso", imageUrl: "/guessmaster/images/bendera/bendera_Burkina-Faso.png" },
    { name: "burundi", imageUrl: "/guessmaster/images/bendera/bendera_Burundi.png" },
    { name: "ceko", imageUrl: "/guessmaster/images/bendera/bendera_Ceko.png" },
    { name: "chad", imageUrl: "/guessmaster/images/bendera/bendera_Chad.png" },
    { name: "chili", imageUrl: "/guessmaster/images/bendera/bendera_Chili.png" },
    { name: "denmark", imageUrl: "/guessmaster/images/bendera/bendera_Denmark.png" },
    { name: "dominika", imageUrl: "/guessmaster/images/bendera/bendera_Dominika.png" },
    { name: "ekuador", imageUrl: "/guessmaster/images/bendera/bendera_Ekuador.png" },
    { name: "el savador", imageUrl: "/guessmaster/images/bendera/bendera_El-Salvador.png" },
    { name: "eritrea", imageUrl: "/guessmaster/images/bendera/bendera_Eritrea.png" },
    { name: "estonia", imageUrl: "/guessmaster/images/bendera/bendera_Estonia.png" },
    { name: "eswatini", imageUrl: "/guessmaster/images/bendera/bendera_Eswatini.png" },
    { name: "ethiopia", imageUrl: "/guessmaster/images/bendera/bendera_Ethiopia.png" },
    { name: "fiji", imageUrl: "/guessmaster/images/bendera/bendera_Fiji.png" },
    { name: "filipina", imageUrl: "/guessmaster/images/bendera/bendera_Filipina.png" },
    { name: "finlandia", imageUrl: "/guessmaster/images/bendera/bendera_Finlandia.png" },
    { name: "gabon", imageUrl: "/guessmaster/images/bendera/bendera_Gabon.png" },
    { name: "gambia", imageUrl: "/guessmaster/images/bendera/bendera_Gambia.png" },
    { name: "georgia", imageUrl: "/guessmaster/images/bendera/bendera_Georgia.png" },
    { name: "ghana", imageUrl: "/guessmaster/images/bendera/bendera_Ghana.png" },
    { name: "grenada", imageUrl: "/guessmaster/images/bendera/bendera_Grenada.png" },
    { name: "guatemala", imageUrl: "/guessmaster/images/bendera/bendera_Guatemala.png" },
    { name: "guinea", imageUrl: "/guessmaster/images/bendera/bendera_Guinea.png" },
    { name: "guenia bissau", imageUrl: "/guessmaster/images/bendera/bendera_Guinea-Bissau.png" },
    { name: "guinea khatulistiwa", imageUrl: "/guessmaster/images/bendera/bendera_Guinea-Khatulistiwa.png" },
    { name: "guyana", imageUrl: "/guessmaster/images/bendera/bendera_Guyana.png" },
    { name: "haiti", imageUrl: "/guessmaster/images/bendera/bendera_Haiti.png" },
    { name: "honduras", imageUrl: "/guessmaster/images/bendera/bendera_Honduras.png" },
    { name: "hongaria", imageUrl: "/guessmaster/images/bendera/bendera_Hongaria.png" },
    { name: "india", imageUrl: "/guessmaster/images/bendera/bendera_India.png" },
    { name: "indonesia", imageUrl: "/guessmaster/images/bendera/bendera_Indonesia.png" },
    { name: "inggris", imageUrl: "/guessmaster/images/bendera/bendera_Inggris.png" },
    { name: "irak", imageUrl: "/guessmaster/images/bendera/bendera_Irak.png" },
    { name: "iran", imageUrl: "/guessmaster/images/bendera/bendera_Iran.png" },
    { name: "islandia", imageUrl: "/guessmaster/images/bendera/bendera_Islandia.png" },
    { name: "israel", imageUrl: "/guessmaster/images/bendera/bendera_Israel.png" },
    { name: "italia", imageUrl: "/guessmaster/images/bendera/bendera_Italia.png" },
    { name: "jamaika", imageUrl: "/guessmaster/images/bendera/bendera_Jamaika.png" },
    { name: "jepang", imageUrl: "/guessmaster/images/bendera/bendera_Jepang.png" },
    { name: "jerman", imageUrl: "/guessmaster/images/bendera/bendera_Jerman.png" },
    { name: "jibuti", imageUrl: "/guessmaster/images/bendera/bendera_Jibuti.png" },
    { name: "kamboja", imageUrl: "/guessmaster/images/bendera/bendera_Kamboja.png" },
    { name: "kamerun", imageUrl: "/guessmaster/images/bendera/bendera_Kamerun.png" },
    { name: "kanada", imageUrl: "/guessmaster/images/bendera/bendera_Kanada.png" },
    { name: "kazakhstan", imageUrl: "/guessmaster/images/bendera/bendera_Kazakhstan.png" },
    { name: "kenya", imageUrl: "/guessmaster/images/bendera/bendera_Kenya.png" },
    { name: "kirgiztan", imageUrl: "/guessmaster/images/bendera/bendera_Kirgizstan.png" },
    { name: "kiribati", imageUrl: "/guessmaster/images/bendera/bendera_Kiribati.png" },
    { name: "kolombia", imageUrl: "/guessmaster/images/bendera/bendera_Kolombia.png" },
    { name: "komoro", imageUrl: "/guessmaster/images/bendera/bendera_Komoro.png" },
    { name: "korea selatan", imageUrl: "/guessmaster/images/bendera/bendera_Korea-Selatan.png" },
    { name: "korea utara", imageUrl: "/guessmaster/images/bendera/bendera_Korea-Utara.png" },
    { name: "kosta rika", imageUrl: "/guessmaster/images/bendera/bendera_Kosta-Rika.png" },
    { name: "kroasia", imageUrl: "/guessmaster/images/bendera/bendera_Kroasia.png" },
    { name: "kuba", imageUrl: "/guessmaster/images/bendera/bendera_Kuba.png" },
    { name: "kuwait", imageUrl: "/guessmaster/images/bendera/bendera_Kuwait.png" },
    { name: "laos", imageUrl: "/guessmaster/images/bendera/bendera_Laos.png" },
    { name: "latvia", imageUrl: "/guessmaster/images/bendera/bendera_Latvia.png" },
    { name: "lebanon", imageUrl: "/guessmaster/images/bendera/bendera_Lebanon.png" },
    { name: "lesotho", imageUrl: "/guessmaster/images/bendera/bendera_Lesotho.png" },
    { name: "liberia", imageUrl: "/guessmaster/images/bendera/bendera_Liberia.png" },
    { name: "libya", imageUrl: "/guessmaster/images/bendera/bendera_Libya.png" },
    { name: "liechtenstein", imageUrl: "/guessmaster/images/bendera/bendera_Liechtenstein.png" },
    { name: "lituania", imageUrl: "/guessmaster/images/bendera/bendera_Lituania.png" },
    { name: "luksemburg", imageUrl: "/guessmaster/images/bendera/bendera_Luksemburg.png" },
    { name: "republik afrika tengah", imageUrl: "/guessmaster/images/bendera/bendera_Republik-Afrika-Tengah.png" },
    { name: "republik demokratik kongo", imageUrl: "/guessmaster/images/bendera/bendera_Republik-Demokratik-Kongo.png" },
    { name: "republik dominika", imageUrl: "/guessmaster/images/bendera/bendera_Republik-Dominika.png" },
    { name: "republik irlandia", imageUrl: "/guessmaster/images/bendera/bendera_Republik-Irlandia.png" },
    { name: "republik kongo", imageUrl: "/guessmaster/images/bendera/bendera_Republik-Kongo.png" },
  ]
};
export default dataImages;
